# Generated by Django 5.1 on 2024-08-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon_support_manager', '0002_remove_ticket_operator_id_ticket_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
