# Generated by Django 5.1 on 2024-08-31 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anon_support_manager', '0004_operator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='operator',
            new_name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_operator',
        ),
    ]
