# Generated by Django 5.1 on 2024-09-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon_support_manager', '0005_rename_operator_ticket_assigned_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='message_history',
            field=models.JSONField(default=list),
        ),
    ]
