# Generated by Django 5.1 on 2024-09-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anon_support_manager', '0007_remove_ticket_message_history_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='user',
        ),
    ]
