# Generated by Django 5.1 on 2024-08-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anon_bot_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BotUser',
        ),
    ]
