# Generated by Django 5.1 on 2024-09-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anon_bot_manager', '0002_rename_user_botuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='is_admin',
        ),
    ]
