# Generated by Django 5.1 on 2024-09-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anon_bot_manager', '0003_remove_botuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='subscription_type',
        ),
    ]
