# Generated by Django 5.1 on 2024-08-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('image_text', 'Image + Text')], max_length=20),
        ),
    ]
