# Generated by Django 5.1 on 2024-08-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_file_text_alter_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
