# Generated by Django 5.1 on 2024-08-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0003_file_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=255)),
                ('subscription_type', models.CharField(default='FREE', max_length=50)),
                ('generated_links', models.IntegerField(default=0)),
                ('join_date', models.DateTimeField()),
                ('is_admin', models.BooleanField(default=False)),
                ('user_consent', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('image_text', 'Image + Text'), ('video', 'video')], max_length=20),
        ),
    ]
