# Generated by Django 5.1 on 2024-08-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0004_botuser_alter_file_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='botuser',
            table='users_db',
        ),
    ]
