# Generated by Django 5.1 on 2024-08-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0005_alter_botuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='botuser',
            table='users',
        ),
    ]
