# Generated by Django 5.1 on 2024-08-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0006_alter_botuser_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotUser',
        ),
    ]
