# Generated by Django 5.1 on 2024-09-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0007_delete_botuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('image_text', 'Image + Text'), ('video', 'Video')], max_length=20),
        ),
    ]
