# Generated by Django 5.1 on 2024-09-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0008_file_is_downloaded_alter_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
