# Generated by Django 5.1 on 2024-09-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0009_file_mime_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='chat_id',
        ),
    ]
