# Generated by Django 5.1 on 2024-09-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0010_remove_file_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
