# Generated by Django 5.1 on 2024-09-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0011_file_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
    ]
