# Generated by Django 5.1 on 2024-09-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0012_file_is_opened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('video', 'Video'), ('audio', 'Audio')], max_length=20),
        ),
    ]
