# Generated by Django 5.1 on 2024-09-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0014_adsbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsbanner',
            name='image',
            field=models.ImageField(upload_to='bnr_recomends/', verbose_name='Изображение (GIF поддерживается)'),
        ),
    ]
