# Second stage: build the Nginx server
FROM nginx

# Copying our .conf files
COPY ./default.conf /etc/nginx/conf.d/default.conf

# Remove the log files to ensure that Nginx creates new ones at the default paths
RUN rm -f /var/log/nginx/access.log /var/log/nginx/error.log && \
    touch /var/log/nginx/access.log /var/log/nginx/error.log && \
    chmod 644 /var/log/nginx/*

# Expose port 80
EXPOSE 80
